spring:
  datasource:
#    url: jdbc:mysql://116.62.223.130:3306/flowable_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    url: jdbc:mysql://116.62.223.130:3306/flowable-ui?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wj@123..*
server:
  port: 8888

